# Generated by Django 5.2.3 on 2025-10-01 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_resstudent_is_agent_resstudent_is_applied_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='universityapplication',
            name='agent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='agent', to='contact.resstudent'),
        ),
        migrations.AddField(
            model_name='universityapplication',
            name='applied_to_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='applied', to='contact.resstudent'),
        ),
        migrations.AlterField(
            model_name='resstudent',
            name='passport_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='universityapplication',
            name='application',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='universityapplication',
            name='student',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='universityapplication',
            name='student_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='student', to='contact.resstudent'),
        ),
    ]
