# Generated by Django 5.2.3 on 2025-10-04 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_travel'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='student_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.resstudent'),
        ),
    ]
