# Generated by Django 5.2.3 on 2025-10-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_academicdetails_payment_refusal_uploaddoc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='period',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
