# Generated by Django 5.2.3 on 2025-10-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_alter_workexperience_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resstudent',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
