# Generated by Django 5.2.3 on 2025-10-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_alter_resstudent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicdetails',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='refusal',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='uploaddoc',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
