# Generated by Django 5.2.3 on 2025-10-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0012_academicdetails_name_payment_name_refusal_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaddoc',
            name='attach_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='doc/'),
        ),
    ]
