# Generated by Django 5.2.3 on 2025-10-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0013_uploaddoc_attach_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='universityapplication',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
